services:
  php:
    build: docker/php
    container_name: php
    ports:
      - "9000:9000" # Redirige le port 9000 du conteneur vers le port 9000 de l'hôte
    volumes:
      - .:/var/www/html # Monte le répertoire local dans /var/www/html du conteneur
    restart: always
    depends_on:
      - db  # Indique que le conteneur `php` dépend du conteneur `db`
    environment:
      DATABASE_URL: ${DATABASE_URL}

  db:
    image: postgres:latest
    container_name: db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}  # Définit l'utilisateur PostgreSQL (config dans le .env)
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}  # Définit le mot de passe PostgreSQL (config dans le .env)
      POSTGRES_DB: ${POSTGRES_DB}  # Définit la base de données PostgreSQL (config dans le .env)
    ports:
      - "5432:5432"  # Redirige le port 5432 du conteneur vers le port 5432 de l'hôte
    volumes:
      - db:/var/lib/postgresql/data

  nginx:
    image: nginx:stable-alpine
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html
      ### Uncomment for nginx project logs
      # - ./var/log/nginx/:/var/log/nginx
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - db

  pgadmin4:
    depends_on:
      - db
    image: elestio/pgadmin:latest
    restart: always
    environment:
      PMA_HOST: db
    env_file:
      - .env
    ports:
      - "5051:80"

# ###> doctrine/doctrine-bundle ###
#   database:
#     image: postgres:${POSTGRES_VERSION:-16}-alpine
#     environment:
#       POSTGRES_DB: ${POSTGRES_DB:-app}
#       # You should definitely change the password in production
#       POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-!ChangeMe!}
#       POSTGRES_USER: ${POSTGRES_USER:-app}
#     healthcheck:
#       test: ["CMD", "pg_isready", "-d", "${POSTGRES_DB:-app}", "-U", "${POSTGRES_USER:-app}"]
#       timeout: 5s
#       retries: 5
#       start_period: 60s
#     volumes:
#       - database_data:/var/lib/postgresql/data:rw
#       # You may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
#       # - ./docker/db/data:/var/lib/postgresql/data:rw
# ###< doctrine/doctrine-bundle ###

volumes:
  db:
# ###> doctrine/doctrine-bundle ###
#   database_data:
# ###< doctrine/doctrine-bundle ###
