name: CI

on:
  push:
    branches: [ "main", "develop" ]

jobs:
  build:
    name: Symfony (PHP 8.2.4)
    runs-on: ubuntu-latest

    services:
      db:
        image: postgres:latest
        env:
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
        ports:
          - 5432/tcp
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 3
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      - name: Install dependencies
        run: composer install --no-progress --prefer-dist
      
      - name: Run unit tests
        run: |
          if [ -f vendor/bin/phpunit ]; then
            vendor/bin/phpunit --coverage-text
          else
            echo "No tests implemented yet."
          fi

  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: success()

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Deploy to VPS
      uses: appleboy/ssh-action@v0.1.8
      with:
        host: ${{ secrets.VPS_HOST }}
        port: ${{ secrets.VPS_PORT }}
        username: ${{ secrets.VPS_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          cd /var/www/bads-club
          git pull origin main
          docker-compose down
          docker-compose up -d --build
